{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteServiceUnreachable"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":1,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/galenit_modulessdk\/autherror\/remoteserviceunreachable"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.galenit.GalenIT-ModulesSDK\/documentation\/GalenIT_ModulesSDK\/AuthError\/remoteServiceUnreachable","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"No overview available."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteServiceUnreachable"}],"title":"AuthError.remoteServiceUnreachable","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:18GalenIT_ModulesSDK9AuthErrorO24remoteServiceUnreachableyA2CmF","modules":[{"name":"GalenIT_ModulesSDK"}]},"hierarchy":{"paths":[["doc:\/\/com.galenit.GalenIT-ModulesSDK\/documentation\/GalenIT_ModulesSDK","doc:\/\/com.galenit.GalenIT-ModulesSDK\/documentation\/GalenIT_ModulesSDK\/AuthError"]]},"references":{"doc://com.galenit.GalenIT-ModulesSDK/documentation/GalenIT_ModulesSDK/AuthError/remoteServiceUnreachable":{"role":"symbol","title":"AuthError.remoteServiceUnreachable","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"remoteServiceUnreachable"}],"abstract":[],"identifier":"doc:\/\/com.galenit.GalenIT-ModulesSDK\/documentation\/GalenIT_ModulesSDK\/AuthError\/remoteServiceUnreachable","kind":"symbol","type":"topic","url":"\/documentation\/galenit_modulessdk\/autherror\/remoteserviceunreachable"},"doc://com.galenit.GalenIT-ModulesSDK/documentation/GalenIT_ModulesSDK":{"role":"collection","title":"GalenIT_ModulesSDK","abstract":[],"identifier":"doc:\/\/com.galenit.GalenIT-ModulesSDK\/documentation\/GalenIT_ModulesSDK","kind":"symbol","type":"topic","url":"\/documentation\/galenit_modulessdk"},"doc://com.galenit.GalenIT-ModulesSDK/documentation/GalenIT_ModulesSDK/AuthError":{"role":"symbol","title":"AuthError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthError"}],"abstract":[],"identifier":"doc:\/\/com.galenit.GalenIT-ModulesSDK\/documentation\/GalenIT_ModulesSDK\/AuthError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AuthError"}],"url":"\/documentation\/galenit_modulessdk\/autherror"}}}